### ISSUE TITLE
Spymaster can't see neutrals

### ISSUE THREAD

**Issue by dickpound** [braican/codenames#3] opened 2020-04-02 01:31 UTC
Gray used to highlight neutral from the spymaster view is indistinguishable from unselected swuares

**Comment by braican** [comment] 2020-04-07 03:06
Fixed by the latest updates to master, released in [1.0.0](https://github.com/braican/codenames/releases/tag/1.0.0). (Duplicate of #2 )

**Closed by braican** 2020-04-07 03:06 UTC
